# Test workflow for python unit tests

name: Pyton Unit Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  unittest:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Tests
        run: python -m unittest -v src/tests/**/*.py
